apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-dodo
  namespace: default
spec: 
  storageClassName: azurefile
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 2Gi
  # selector:
  #   matchLabels:
  #     coder: dodo
