apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-dodo
  namespace: default
provisioner: file.csi.azure.com
parameters: 
  storageAccount: kohlisa
  resourceGroup: kohli-rg1
  secretName: dodo-secret
  skuName: Standard_LRS
allowVolumeExpansion: true
reclaimPolicy: Retain

